name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Run tests
    - name: Run Tests
      run: npm test -- --watchAll=false

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    # Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-ts-app:latest .

    # Push Docker image
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-ts-app:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    # Deploy (customize deployment steps as needed)
    - name: Deploy Application
      run: echo "Deployment step here (e.g., SSH, Kubernetes, AWS CLI, etc.)"
